### ISSUE TITLE
Symbol not found: _pango_cairo_create_layout

### ISSUE THREAD

**Issue by narendrachettri** [ManimCommunity/ManimPango#104]
i am getting this error while running manim
i have python 3.11.5
maninpango 0.4.4
manim 0.17.3
pango 1.50.14
py3cairo 1.25.0
scipy 1.11.3 
ffmpeg 6.0_1

    from .cmanimpango import *
ImportError: dlopen(/Users/endra/Manim/v0.17.3/venv/lib/python3.11/site-packages/manimpango/cmanimpango.cpython-311-darwin.so, 0x0002): Symbol not found: _pango_cairo_create_layout
  Referenced from: <542EB9D6-9D9E-3A46-A342-A55098D19BB0> /Users/endra/Manim/v0.17.3/venv/lib/python3.11/site-packages/manimpango/cmanimpango.cpython-311-darwin.so
  Expected in:     <no uuid> unknown

**Comment by naveen521kk** [comment]
@narendrachettri  Can you whether this occurs in the current release?
