### ISSUE TITLE
Creating Text Mobject retrieves TypeError (manimpango.text2svg has incorrect argument typing)

### ISSUE THREAD

**Issue by mkashirin** [ManimCommunity/ManimPango#106]
Hello. 
I'm having a trouble rendering a Text Mobject. An attempt of creating a Text Mobject retrieves TypeError because `manimpango.text2svg` function has incorrect argument typing (`size: int, line_spacing: int` istead of both being` float`). Traceback is represented on screenshots attached.
The problem is I just don't know how to save any type of changes made to them `.pyx` files.

**Steps to reproduce the problem:**
  1. install Anaconda 3 on Windows 11 Pro;
  2. install Manim with the following command `conda install -c conda-forge manim` on Conda's Python 3.11.6;
  3. try to run the code from the Screenshot 1 or render the text typing `manim -pqh scene.py TextAnimation`.

**Screenshots:**
  screenshot 1: ![Снимок экрана 2023-10-13 191126](https://github.com/ManimCommunity/ManimPango/assets/88917554/d97ab3cf-6002-4cea-9c10-e04e125d758d);
  screenshot 2: ![Снимок экрана 2023-10-13 191315](https://github.com/ManimCommunity/ManimPango/assets/88917554/79bc833e-01ac-46b4-a1a8-b1c52a5bb071).

Thanks for your response.

**Comment by uwezi** [comment]
don't just use screenshots - especially not for your code!

```python
class TextAnimation(Scene):
    def construct(self):
        text = Text("Book Antiqua", font="Book Antiqua")
        self.play(Write(text))
        self.play(Unwrite(text))
```

**Comment by uwezi** [comment]
Ok, I finally updated my Python to a recent Python 3.11 (not Anaconda, but plain Windows-version of Python from python.org) and I still cannot reproduce your problem.

**Comment by mkashirin** [comment]
Basically, I can try installing Manim via pip into pure Python venv. Not sure it'll help, but still...

**Comment by mkashirin** [comment]
So, I installed it manually into the pure Python virtual environment, created via PyCharm, and everything works just perfect. It seems like the problem with either VSCode or Conda itself.
Thanks for your response.

**Comment by naveen521kk** [comment]
Cython 3 started to enforce type-checking more strictly which caused this issue. On normal Python, the wheel from PyPI would be installed which should be built with Cython 0.x. Conda seems to have built this project with Cython 3. 

https://github.com/ManimCommunity/ManimPango/pull/105 seems to have fixed most of the issues, I'll do a bit more testing and release a new version.

I'll keep this open for a bit till I release a new version.

**Comment by alexandross** [comment]
I am using conda, I updated today both conda and the manimCE environment inside conda, and I started to get this error. It was working fine previously. Any assistance would be greatly appreciated. Thank you!

**Comment by behackl** [comment]
> I am using conda, I updated today both conda and the manimCE environment inside conda, and I started to get this error. It was working fine previously. Any assistance would be greatly appreciated. Thank you!

Wait for the upcoming release, or just try and run `pip install manimpango --force`.

**Comment by alexandross** [comment]
Thank you! I just installed manim in my "base" environment (outside of the "manimCE" conda environment) using "pip3 install manim" and it works. I will keep updating the manimCE conda environment, hopefully a future update will fix it.

**Comment by smadikanti** [comment]
Issue still persists

**Comment by uwezi** [comment]
@smadikanti 
> Issue still persists

well, the issue has been fixed as reported by others. 

Which version of Manim and which version of Python are you using on what operating system?
And did you follow the advice above to run `pip install manimpango --force`?
