### ISSUE TITLE
cairo.h: No such file or directory

### ISSUE THREAD

**Issue by Shoxx98** [ManimCommunity/ManimPango#107]
when installing on manjaro through pamac, this error occurs and building fails.

**Comment by Shoxx98** [comment]
full log:

Building python-manimpango...
==> Making package: python-manimpango 0.4.4-2 (Thu 02 Nov 2023 02:23:14 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found ManimPango-0.4.4.tar.gz
==> Validating source files with sha512sums...
    ManimPango-0.4.4.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting ManimPango-0.4.4.tar.gz with bsdtar
==> Starting prepare()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
/var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/setup.py:98: RuntimeWarning: pkg-config doesn't exists or doesn't seem to work
We assume that you give the compiler flags using
corresponding environment variables.
  warnings.warn(
/var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/setup.py:98: RuntimeWarning: pkg-config doesn't exists or doesn't seem to work
We assume that you give the compiler flags using
corresponding environment variables.
  warnings.warn(
warning: manimpango/register_font.pxd:23:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
warning: manimpango/register_font.pyx:69:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
Compiling /var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/manimpango/cmanimpango.pyx because it changed.
Compiling /var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/manimpango/enums.pyx because it changed.
Compiling /var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/manimpango/register_font.pyx because it changed.
[1/3] Cythonizing /var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/manimpango/cmanimpango.pyx
[2/3] Cythonizing /var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/manimpango/enums.pyx
[3/3] Cythonizing /var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/manimpango/register_font.pyx
running build
running build_py
creating build
creating build/lib.linux-x86_64-cpython-311
creating build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/_version.py -> build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/__init__.py -> build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/utils.py -> build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/register_font.pxd -> build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/cairo.pxd -> build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/pango.pxd -> build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/glib.pxd -> build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/cmanimpango.pxd -> build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/register_font.pyx -> build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/cmanimpango.pyx -> build/lib.linux-x86_64-cpython-311/manimpango
copying manimpango/enums.pyx -> build/lib.linux-x86_64-cpython-311/manimpango
running build_ext
building 'manimpango.cmanimpango' extension
creating build/temp.linux-x86_64-cpython-311
creating build/temp.linux-x86_64-cpython-311/var
creating build/temp.linux-x86_64-cpython-311/var/tmp
creating build/temp.linux-x86_64-cpython-311/var/tmp/pamac-build-jonas
creating build/temp.linux-x86_64-cpython-311/var/tmp/pamac-build-jonas/python-manimpango
creating build/temp.linux-x86_64-cpython-311/var/tmp/pamac-build-jonas/python-manimpango/src
creating build/temp.linux-x86_64-cpython-311/var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4
creating build/temp.linux-x86_64-cpython-311/var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/manimpango
gcc -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIC -I/usr/include/python3.11 -c /var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/manimpango/cmanimpango.c -o build/temp.linux-x86_64-cpython-311/var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/manimpango/cmanimpango.o
/var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/manimpango/cmanimpango.c:1199:10: fatal error: cairo.h: No such file or directory
 1199 | #include "cairo.h"
      |          ^~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by naveen521kk** [comment]
> /var/tmp/pamac-build-jonas/python-manimpango/src/ManimPango-0.4.4/setup.py:98: RuntimeWarning: pkg-config doesn't exists or doesn't seem to work

It looks like you've not installed `pkg-config` and it was the cause of this failure. Please get in touch with AUR maintainers to add it as a dependency. Thanks!
