### ISSUE TITLE
Unable to install manim, manimpango

### ISSUE THREAD

**Issue by mahdoosh1** [ManimCommunity/ManimPango#108]
Console gives me error that "pangocairo >= 1.30.0 is required."

i tried installing pango with "pkg install libpango1.0-dev" in termux and it said "Unable to find a repository with name libpango1.0-dev"

**Comment by mahdoosh1** [comment]
I tried it in Pydroid 3 and didnt work either

**Comment by mahdoosh1** [comment]
How can i download and install libpango1.0-dev from local file?

**Comment by mahdoosh1** [comment]
There was libpangomm-1.4 and libpangomm-2.48
I tried installing them but still pangocairo missing.

**Comment by mahdoosh1** [comment]
tried installing pycairo,
still not fixed

**Comment by naveen521kk** [comment]
I'm not sure about termux, but Pango along with its development headers is a required dependency. Maybe you can try and compile Pango from source?

**Comment by mahdoosh1** [comment]
> I'm not sure about termux, but Pango along with its development headers is a required dependency. Maybe you can try and compile Pango from source?

I may can do it, but how?

**Comment by mahdoosh1** [comment]
> How can i download and install libpango1.0-dev from local file?

This would be helpful

**Comment by naveen521kk** [comment]
> > I'm not sure about termux, but Pango along with its development headers is a required dependency. Maybe you can try and compile Pango from source?
> 
> I may can do it, but how?

Download the source code from https://download.gnome.org/sources/pango/1.51/pango-1.51.0.tar.xz and then extract it. You would need meson and ninja to compile and see https://mesonbuild.com/Quick-guide.html#compiling-a-meson-project on how to.

**Comment by naveen521kk** [comment]
Since there's no reply, I'll consider this as fixed. Feel free to open a new issue or jump over at [Discord](https://manim.community/discord) to ask for help if you've any other issues.
