### ISSUE TITLE
test/cases directory is omitted from released tar

### ISSUE THREAD

**Issue by Groctel** [ManimCommunity/ManimPango#109]
I'm adding a `check` function to the [AUR package](https://aur.archlinux.org/packages/python-manimpango) and I've found that the tests fail due to the directory `test/cases` not existing in the released tar. For now, I'm manually cloning the repository and running `pytest` from there. Is there a chance you could patch the release to include this missing directory?

Thanks!

**Comment by naveen521kk** [comment]
Hey, sorry missed the notification for this. I'll fix this in the next release, when I find some time. Thanks!

**Comment by Groctel** [comment]
It works, thank you!
