### ISSUE TITLE
Can't install manim with Python 3.13

### ISSUE THREAD

**Issue by latenitecoding** [ManimCommunity/ManimPango#114]
Hey everyone! I just wanted to let you know that you can't currently install manim on Python 3.13 because the build dependency on manimpango doesn't have any listed versions of manimpango that work for Python 3.13. Still works great on Python 3.12.
[manim_install_log.txt](https://github.com/user-attachments/files/17492815/manim_install_log.txt)

**Comment by behackl** [comment]
Thanks for the report, we are aware of the issue. The problem has already been fixed for ManimPango, there are a bunch of other dependencies that have no suitable release candidate for Python 3.13 yet. We will release a new version of Manim as soon as these issues are resolved.
