### ISSUE TITLE
Removing Linux Wheels

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/ManimPango#27]
This issue is for tracking and discussing removing the manylinux wheel provided by us and uploaded to PyPI.
We had already been warning users about this [here](https://github.com/ManimCommunity/ManimPango#note).

## Issue

On Linux, Pango is something that is part of the system itself being GNOME, so us packing Pango in wheels provided causes weird issues.

- Packing an old version of Pango, rather than the latest one.
- Once reported by behackl that a folder with fontconfig cache's being created in CWD, but also reported it was fixed.
- Causing SegFaults when used with ManimGL on Arch, https://github.com/3b1b/manim/issues/1387 cc @eulertour 
- Causing problem on launching ManimGL itself on Debian and it's derivatives, https://github.com/3b1b/manim/issues/1391 cc @einarf 

There could be many more please feel free to inform me.

## Cause
The main cause of this problem is providing wheels which contain Pango and pip preferring to install wheel rather than compiling from source. The main reason I was tempted to build wheels was because of ReadtheDocs builds in ManimCommunity Docs doesn't have the Pango dev version installed...

## Solution

Not to upload manylinux wheels to PyPI. Instead of that, uploading those wheels to Github Release can be done. On the ReadtheDocs build for ManimCommunity docs, those wheels can be hyperlinked in the requirements.txt file or set up a Conda Env so that Pango is provided by Conda.

## Process

- [x] ~Editing [Github Action configuration](https://github.com/ManimCommunity/ManimPango/blob/main/.github/workflows/build.yml) for not producing them and updating the ReadMe. PR made https://github.com/ManimCommunity/ManimPango/pull/29~
- [x] ~Updating installation docs at ReadMe PR made https://github.com/ManimCommunity/ManimPango/pull/29~
- [x] ~Updating installation docs at ManimCommunity manim. PR made https://github.com/ManimCommunity/manim/pull/1060~
- [x] ~Updating installation docs at 3b1b's manimgl. PR made https://github.com/3b1b/manim/pull/1421~
- [x] ~Updating requirements.txt in ManimCommunity's manim's ReadtheDocs build, can be done only after release. PR made https://github.com/ManimCommunity/manim/pull/1067~

There could be much more work feel free to edit this message.

**Comment by einarf** [comment]
Thanks for creating this issue. I've had several people poking me about it. With wheels on Ubuntu/Debian there is stack corruption happening for some reason. The outcome is pretty random. Deadlock, segfault or it magically working out of pure luck. Compiling from source solved the issue.

I'm guessing Grant should be notified that the install instructions for Linux are slightly different? Can just add a link to panimpango readme in the 3b1b/manim. Anything to avoid 1000 new questions and issues 😄

**Comment by naveen521kk** [comment]
> I'm guessing Grant should be notified that the install instructions for Linux are slightly different? Can just add a link to panimpango readme in the 3b1b/manim. Anything to avoid 1000 new questions and issues smile

That can be done, I will make a PR to update their install instructions. 

Also, will removing the wheels cause any problems, I think only readthedocs build has, and I had a solution for that in the original comment, if not I will remove them in the next release.
Also, on a side note, I have noticed that pip prefers wheels by default, in that case not publishing wheel for a version, will `pip` download wheels of old release then?

**Comment by einarf** [comment]
Yup. Pip will look for wheels first, then fall back to source distribution. I think `setup.py install` might only grab source distribution still. If no version constraint it will pick the latest release regardless of wheels or not.

**Comment by naveen521kk** [comment]
Thanks, then I think wheels can be removed in the next release and I am working on it.

**Comment by naveen521kk** [comment]
There will be a new release after #31 is merged which will not have wheels.

**Comment by naveen521kk** [comment]
@einarf This shouldn't be a problem now, there is a [new release](https://github.com/ManimCommunity/ManimPango/releases/tag/v0.2.4) published a few minutes ago, which didn't upload wheels for linux.
