### ISSUE TITLE
Using Meson Build System

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/ManimPango#45]
Currently we are setuptools like any other python project, which is fine, but I am strangely attracted to [Meson](https://mesonbuild.com/), as a build system.
Meson is fast, other than that only feature I see, which is so hard to do with setuptools is that we can create C programs to for the testsuites. What I mean is we can write C programs to generate SVG files and compare it with what we generate. That should surely work because we are generating things in the same environment and testing the same.

While doing this would mean maintaining two different build system, one setuptools and other Meson, but I think Meson setup scripts are so easy to maintain than what we do at setuptools, also meson has subprojects, which in a way helps the users to build pango while installing manimpango, say they are on old linux, this may help.

Thoughts about it @PhilippImhof ?

**Comment by PhilippImhof** [comment]
I have absolutely no opinion on this topic, because I have never used Meson. Having two build systems to maintain seems bad to me, however.

**Comment by naveen521kk** [comment]
> Having two build systems to maintain seems a bad idea to me, however.

Indeed yes, meson is so new to python, so we can't use it to create wheels. But still has its own advantages though.

**Comment by naveen521kk** [comment]
I think this would help a lot. Let me see if I can build wheels from meson itself. If I can do that this would be the best approach in long run.

**Comment by naveen521kk** [comment]
I am planing to implement this in #48.

**Comment by naveen521kk** [comment]
Feels like there are lot of things that are *not* going to work with this setup, so I think I am not going to do that.

**Comment by naveen521kk** [comment]
Looks like scipy has moved to Meson now. https://github.com/scipy/scipy/pull/14847

**Comment by rgommers** [comment]
Wheel creation still has sharp edges, but we plan to fix that over the next weeks/months. Unless you're in a hurry I would recommend to wait for a bit till we've tested everything for SciPy.

**Comment by naveen521kk** [comment]
> Wheel creation still has sharp edges, but we plan to fix that over the next weeks/months. Unless you're in a hurry I would recommend to wait for a bit till we've tested everything for SciPy.

Thanks, yeah we would probably wait for SciPy to actually make a release with meson support and wheels built with meson. Also, wish you a happy new year 🎉 .

**Comment by rgommers** [comment]
You too, happy new year!
