### ISSUE TITLE
Showing Errors in Markup if any

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/ManimPango#57]
We currently have a way to check whether the markup is valid or not, but that can be extended to having error messages that is understandable on where is the error is.
I have something working https://github.com/ManimCommunity/ManimPango/blob/cf13f34d4eec59e54143900e0a545d9c6ca0052f/manimpango/layout/utils.pyx which working on #48

**Comment by naveen521kk** [comment]
@PhilippImhof what do you think about this? Can we break the API and release a major version(v0.3.0) or add an auxiliary function that manim will call if the `MarkupUtils.validate` fails?

**Comment by PhilippImhof** [comment]
I think we can safely assume that ManimPango is almost exclusively used by Manim, so breaking the API should not be a big deal. And among 0.x versions, people generally know breaking changes are likely to happen. I would go for it.
