### ISSUE TITLE
libpango-1.0.so.0: undefined symbol: hb_buffer_set_invisible_glyph

### ISSUE THREAD

**Issue by gschramm** [ManimCommunity/ManimPango#63]
Hi all,

I installed all the dependencies on ubuntu 20.04 following the install guide and manimce via ```pip install manim```. My installed manim version is 0.8 and manimpange is 0.3.  When I run 
```
from manim import *
```
I get the error:

---

ManimPango could not import and load the necessary shared libraries.
This error may occur when ManimPango and its dependencies are improperly set up.
Please make sure the following versions are what you expect:

ManimPango v0.3.0, Python v3.7.7

Original error: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: hb_buffer_set_invisible_glyph

---

Any idea what is causing this?

Georg

**Comment by naveen521kk** [comment]
Hi, sorry for the super delayed response I missed this notification. 
`hb_buffer_set_invisible_glyph` is a symbol from harfbuzz and the error seems to point that `libpango-1.0.so.0` has a reference to it but it is missing. I think the simplest, fix I would suggest is force reinstalling ManimPango.
```sh
pip install ManimPango --force --no-cache
```

Hope this helps :)

**Comment by tivnanmatt** [comment]
I'm having this same issue and reinstalling manimpango did not help
