### ISSUE TITLE
Symbol not found: ___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by mforbes** [ManimCommunity/ManimPango#73]
With Mac OS X 10.14.6, I get the following error with "ManimPango v0.4.0.post1, Python v3.9.7":

```
Original error: dlopen(/.../lib/python3.9/site-packages/manimpango/cmanimpango.cpython-39-darwin.so, 2): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /.../lib/python3.9/site-packages/manimpango/.dylibs/libX11.6.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /.../lib/python3.9/site-packages/manimpango/.dylibs/libX11.6.dylib
```

Most likely the key is that `libX11.6.dylib (which was built for Mac OS X 11.0)`, and downgrading to `v0.4.0.post0` fixes the issue.

Not sure if there is something to be done here, but is there any strategy for pinning appropriate versions in a platform dependent way, either with Conda, poetry, or pip?

**Comment by naveen521kk** [comment]
So something is wrong with the `v0.4.0.post1` version and not `v0.4.0.post0`? I'll check the build logs to see if there is any issue.

**Comment by naveen521kk** [comment]
Hmm, yeah checking build log something is broken
```
  /usr/local/Cellar/libx11/1.7.3.1/lib/libX11-xcb.1.dylib
  /usr/local/Cellar/libx11/1.7.3.1/lib/libX11.6.dylib
  /usr/local/Cellar/libxau/1.0.9/lib/libXau.6.dylib
  /usr/local/Cellar/libxcb/1.14_1/lib/libxcb-render.0.0.0.dylib
  /usr/local/Cellar/libxcb/1.14_1/lib/libxcb-shm.0.0.0.dylib
  /usr/local/Cellar/libxcb/1.14_1/lib/libxcb.1.1.0.dylib
  /usr/local/Cellar/libxdmcp/1.1.3/lib/libXdmcp.6.dylib
```
These libs weren't included in previous release. Thanks for reporting. I'll fix soon.

**Comment by naveen521kk** [comment]
This was because of a new version of [meson](https://mesonbuild.com), which added support for finding Xlib, so I have pinned the previous version for now.

**Comment by naveen521kk** [comment]
@mforbes can you test the wheels from [here](https://github.com/ManimCommunity/ManimPango/suites/5079352172/artifacts/151317899) from CI run of #74?

**Comment by mforbes** [comment]
@naveen521kk Seems to work with python3.9.  I will try the others and do a little more comprehsnive testing.

**Comment by naveen521kk** [comment]
> Let me know if you want me to try to run a full test suite. I have not done that before, but probably could.

I don't think it's needed, just running import should be enough.

> Will this be released as post2 eventually?

Yup.

**Comment by naveen521kk** [comment]
The new release(`.post2`) fixes this, right?

**Comment by mforbes** [comment]
Works for me.  Thanks!
