### ISSUE TITLE
Building/dependencies

### ISSUE THREAD

**Issue by ma-laforge** [ManimCommunity/ManimPango#90]
On fresh Ubuntu 22.04 install:

`apt install libpango1.0-dev pkg-config python3-dev`

was insufficient to `pip install manimpango`

Had to add:
`apt install build-essential`

for it to work.

**Comment by naveen521kk** [comment]
Yeah it's assumed that you have a working C/C++ compiler and it's mentioned in the docs/README https://github.com/ManimCommunity/ManimPango#linuxmacos
