### ISSUE TITLE
Problem with MANIM installation.

### ISSUE THREAD

**Issue by Naisvk** [ManimCommunity/ManimPango#94]
I'm a newbie to the community here; I may need help in installing the MANIM software, which follows:

>       #clang: error: no such file or directory: 'manimpango/cmanimpango.c'
>       clang: error: no input files
>       error: command '/usr/bin/clang' failed with exit code 1
>       [end of output]
>       note: This error originates from a subprocess, and is likely not a problem with pip.
>       ERROR: Failed building wheel for **manimpango**
>       Failed to build manimpango
>       ERROR: Could not build wheels for **manimpango**, which is required to install pyproject.toml-based projects

**Comment by rtfb** [comment]
I'm observing the same on an M1 Mac, with OSX v12.4, Python v3.10.7 and pip v22.2.2.
Same happens if I `pip3 install manimpango`, and `pip3 install .` from master.

**Comment by ad-chaos** [comment]
Please join the server https://discord.gg/CKqCdhqN, its much easier to talk and debug there.

I'll update any solution here if we manage to come to one.

**Comment by rtfb** [comment]
Thanks a lot for a tip, @y-mx-b, installing `Cython` helped!

@Naisvk, try it out as well.

**Comment by Naisvk** [comment]
Huh, it actually works. Thanks so much for your trick, @y-mx-b!

**Comment by ad-chaos** [comment]
If anyone in the future is seeing this, please don't install cython and come join the discord server 😅
